### ISSUE TITLE
1.13.0 introduced bug in `openssl::export::pkcs12`

### ISSUE THREAD

**Issue by walkamongus** [camptocamp/puppet-openssl#110]
The `in_pass` and `out_pass` params are set to Boolean at https://github.com/camptocamp/puppet-openssl/blob/master/manifests/export/pkcs12.pp#L19, which doesn't allow for inputting the passwords. The param type should probably be `Variant[Boolean, String]` or something similar.

**Comment by raphink** [comment]
Thanks! Actually, the mistake comes from the default value being `false`, when it should be `undef` for a string. I'll fix that.
