### ISSUE TITLE
No way to set desired openssl package version

### ISSUE THREAD

**Issue by edestecd** [camptocamp/puppet-openssl#35]
May I suggest adding an $ensure paramter similar to:

```puppet
class openssl (
  $package_ensure => present,
){
}

class openssl::packages {
  package { 'openssl':
    ensure => $openssl::package_ensure,
  }
}
```

If no one has any objection, I will make the change and submit a pull request.

Any thoughts?

**Comment by raphink** [comment]
I'm good with that, go ahead and attach code.
