### ISSUE TITLE
Configure top-level class?

### ISSUE THREAD

**Issue by jorymil** [camptocamp/puppet-openssl#42]
Let's say that we have a separate tool for managing certificates (Comodo Certificate Manager in our case) and that we want to manage our openssl.cnf independently of any specific certificate we generate.  Being able to configure the top-level class in this way would be exceptionally helpful, especially for setting package versions or site-wide options.  I suppose that this could be done within the context of a private key (SSL's useless without one), but being able to configure the overall class and not just individual keys/csrs/ certs would be valuable.

**Comment by raphink** [comment]
So you'd want an option to avoid managing the conf file, right?

**Comment by jorymil** [comment]
Sorry--the other way around.  I'd like to be able to manage the config file
without having to create certificates, private keys, or CSRs that we don't
necessarily need, or that might change in the future.  We definitely need
certs; we just don't want the main config file tied to any specific cert.

John

**Comment by jorymil** [comment]
I'm writing a barebones module right now; once I've got a better idea about
which parameters I need, I'll submit a patch or two back upstream.

John

**Comment by raphink** [comment]
OK then, looking forward to the patch.
