### ISSUE TITLE
Can't add SAN records

### ISSUE THREAD

**Issue by mvar** [camptocamp/puppet-openssl#44]
I just wanted to create single certificate for multiple domains, but that feature doesn't seem to work.

My Puppet manifest:

``` puppet
openssl::certificate::x509 { 'test1':
  country      => 'US',
  organization => 'Dev',
  commonname   => 'domain.tld',
  altnames     => ['anotherdomain.tld', 'subdomain.domain.tld'],
}
```

Created certificate contains `domain.tld` as "Common Name", but there are no records about SAN (Subject Alternative Names).

**Comment by bijanvakili** [comment]
@mvar I eventually figured this out by looking at the comments in the [sample openssl.cnf](http://web.mit.edu/crypto/openssl.cnf) that comes with most openssl packages.  If you [look at the default template](https://github.com/camptocamp/puppet-openssl/blob/master/templates/cert.cnf.erb#L17) that is used by this Puppet module, it only includes a ```req_extensions``` directive.  This will only add the extensions (such as the ```altnames```) to the certificate *request*, not the generated certificate.  So you need an  ```x509_extensions``` directive to also add everything to the *certificate*.

A temporary workaround would be to use your own template configuration file (via the ```cnf_tpl``` attribute as the README describes) with the same template content but with this inserted this on line 18:

    x509_extensions = req_ext

I'd be happy to make a pull request to update the default template if the authors for this module agree that this should be the default behavior.
