### ISSUE TITLE
Add openssl_version fact

### ISSUE THREAD

**Issue by edestecd** [camptocamp/puppet-openssl#57]
Will you accept a PR for an openssl version fact?

**Comment by raphink** [comment]
If you provide the code + the tests, and you don't use it in the Puppet code of this module (to prevent chicken/egg issues), then sure.

**Comment by ndelic0** [comment]
Any plans for adding support method for PE2015.2.3? After last commit I'm getting following error:
Error: Facter: error while resolving custom fact "openssl_version": undefined method `[]' for nil:NilClass

**Comment by raphink** [comment]
@ndelic0 Can you open an issue for that?
