### ISSUE TITLE
Error: Facter: error while resolving custom fact "openssl_version"

### ISSUE THREAD

**Issue by ndelic0** [camptocamp/puppet-openssl#62]
Any plans for adding support method for PE2015.2.3? After merging following https://github.com/camptocamp/puppet-openssl/commit/5a57c6729b8b148e0c0bf78f319fdb9083104ba2 we're following error:
Error: Facter: error while resolving custom fact "openssl_version": undefined method `[]' for nil:NilClass

**Comment by edestecd** [comment]
I get the same error in Foss 3.8.6

**Comment by mike-es** [comment]
I'm having the same issue with PE 2015.3.3 on RHEL 6
