### ISSUE TITLE
Errors with inifile 3.0

### ISSUE THREAD

**Issue by jyaworski** [camptocamp/puppet-openssl#67]
``` puppet
Error: Could not run Puppet configuration client: /usr/lib/ruby/gems/1.8/gems/inifile-3.0.0/lib/inifile.rb:558: undefined (?...) sequence: /\A"(.*)(?<!\\)"\z/
```

This is on the current HEAD.

**Comment by jyaworski** [comment]
Update: downgrading inifile to 2.0.2 worked on 1.8.7.

Suggestions:

Document that ruby 1.8.7 needs ijnifile 2.0.0.

Change that syntax to be 1.8.7 compatible.

**Comment by raphink** [comment]
Either will do, do you want to provide PR for that?
