### ISSUE TITLE
Unable to use openssl::certificate::x509 without password

### ISSUE THREAD

**Issue by cliff-wakefield** [camptocamp/puppet-openssl#76]
Have been trying to create a new certificate with no passphrase on the private key.

Passing 'password' as undef doesn't work.
Not passing 'password' doesn't work.

It results in the following

Enter PEM pass phrase:

**Comment by cliff-wakefield** [comment]
Even in debug mode I can't see how its calling openssl to create the certificate.

**Comment by cliff-wakefield** [comment]
Ok if I clean out any previous certs it does work.  Seems the existing private key wasn't overwritten, so attempts to create the x509 were still prompting for the password.

**Comment by raphink** [comment]
So it was not really a *new* certificate as initially reported then, but rather modifying an existing certificate to remove its password, right?
