### ISSUE TITLE
No password on openssl::export::pkcs12 not working as expected

### ISSUE THREAD

**Issue by edestecd** [camptocamp/puppet-openssl#81]
The default of false for out_pass does not work.

Per this, you need to specify a blank password to get no password.
This is our experience as well.
http://stackoverflow.com/questions/27497723/export-a-pkcs12-file-without-an-export-password

A current workaround is to set 
```puppet
out_pass => ''
```

However this is not a permanent solution and the default should really work.

I think this code should fix it:
```puppet
      $passout_opt = $out_pass ? {
        false   => '-passout pass:',
        default => "-passout pass:${out_pass}",
      }
```

**Comment by edestecd** [comment]
Another option is to change the default to undef:
```puppet
define openssl::export::pkcs12(
  $basedir,
  $pkey,
  $cert,
  $ensure    = present,
  $chaincert = false,
  $in_pass   = false,
  $out_pass  = undef,
) {
```

**Comment by edestecd** [comment]
Let me know your opinion and I'll gladly make a PR.

**Comment by raphink** [comment]
I think a PR for that would be fine. @cjeanneret do you see any issue with that?

**Comment by raphink** [comment]
Imo, the `undef` option would be better.

**Comment by raphink** [comment]
Any interest in providing a PR for this still?
