### ISSUE TITLE
dhparam doesn't work without 'ensure'

### ISSUE THREAD

**Issue by anthonyheckmann** [camptocamp/puppet-openssl#90]
This doesn't create the file unless `ensure` is uncommented, which should be the default operation.
```
dhparam { '/etc/openvpn/dh2048.pem': 
    size         => 2048,
    require    => Package['openvpn'],
    # ensure => 'present'    
 }
```

**Comment by anthonyheckmann** [comment]
It might be I'm just not using it correctly. Though the docs say this:
```
dhparam { '/etc/openvpn/dh2048.pem': 
    size         => 2048
}
```
should work.

**Comment by raphink** [comment]
OK. Requiring `ensure` doesn't shock me, so would it be acceptable to update the docs?

**Comment by anthonyheckmann** [comment]
Seems reasonable. Not sure what happens when no params are used at all.
Both cases might need to be updated.

**Comment by tlcowling** [comment]
@anthonyheckmann I think sticking the ```openssl::``` at the beginning is what you want so it collects 'present' by default from the puppet type.  This happened to me too just before AND also while doing stuff with openvpn!

```puppet
openssl::dhparam { '/etc/openvpn/dh2048.pem': 
    size         => 2048
}
```

Agree with updating the doc to reflect this!
