### ISSUE TITLE
Regenerate dhparams if the key size has changed

### ISSUE THREAD

**Issue by tlcowling** [camptocamp/puppet-openssl#91]
If the ‘size’ of the resource has changed, new dhparams should be generated.

Why?  Given the logjam vulnerability and to prevent regression in the event of a dhparams file being manually overwritten.

This would work nicely for the case where the user, having managed their dhparams via this lovely puppet module (like myself), needs to upgrade a whole bunch of dhparams in one go…

Similarly, since regenerating based on size will require puppet to parse a dhparams file I think it would also make sense for an invalid /corrupted dhparams file to be regenerated. 

I've done a little experimentation so far making the type use size as a property and get the following:

Given a dhparam managed like this in puppet
```puppet
dhparam { '/tmp/dhparam.pem':
    size   => 2048,
}
```
and then overriding it:
```
openssl dhparam -out /tmp/dhparam.pem 16
```
I get the following:

```
Notice: /Stage[main]/Openssl/Dhparam[/tmp/dhparam.pem]/size: size changed '16' to '2048'
Notice: Applied catalog in 46.97 seconds
```
similarly for a file that is not a valid dhparams :
```puppet
Notice: /Stage[main]/Openssl/Dhparam[/tmp/dhparam.pem]/size: size changed '' to '2048'
Notice: Applied catalog in 67.06 seconds
```

**Comment by raphink** [comment]
I'd welcome a PR for that.
