### ISSUE TITLE
ssl_pkey should default to ensure=>present

### ISSUE THREAD

**Issue by kasimon** [camptocamp/puppet-openssl#94]
As of version v1.10.0,

```
ssl_pkey { '/path/to/private.key': }
```

does not create a private key but 

```
ssl_pkey { '/path/to/private.key':
  ensure => 'present',
}
```

does. `ensure => present` should be the default.

**Comment by raphink** [comment]
Fair enough. This requires to edit the `ensurable` block to define the default value. PR welcome.
