### ISSUE TITLE
ssl_pkey file permissions should default to 0600 and should be changeable

### ISSUE THREAD

**Issue by kasimon** [camptocamp/puppet-openssl#95]
As of v1.10.0, 

```
ssl_pkey { '/path/to/private.key':
  ensure => 'present',
}
```

creates a private key file with 0644 permissions. Given the security critical role of private keys, this should default to 0600 and be changeable with the usual `user`, `group` and `mode` options.

**Comment by kasimon** [comment]
As I just recognized, you can use a file resource to accomplish this:

```
  $private_key = '/path/to/private.key'
  ssl_pkey { $private_key:
    ensure => 'present',
  }
  file { $private_key:
    ensure => file,
    owner  => 'root',
    group  => 'root',
    mode   => '0600',
  }
```

Probably this should be added to the documentation.

**Comment by raphink** [comment]
I'd definitely welcome a PR against the README for that.
